[package]
name = "rendy-project-euler"
version = "0.1.0"
authors = ["heyimrendy <yrendykurniawan@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
